// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain_mocks

import (
	"context"
	"g6/blog-api/Domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBlogCommentRepository creates a new instance of MockBlogCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlogCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlogCommentRepository {
	mock := &MockBlogCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlogCommentRepository is an autogenerated mock type for the BlogCommentRepository type
type MockBlogCommentRepository struct {
	mock.Mock
}

type MockBlogCommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlogCommentRepository) EXPECT() *MockBlogCommentRepository_Expecter {
	return &MockBlogCommentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockBlogCommentRepository
func (_mock *MockBlogCommentRepository) Create(ctx context.Context, comment *domain.BlogComment) (*domain.BlogComment, *domain.DomainError) {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.BlogComment
	var r1 *domain.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.BlogComment) (*domain.BlogComment, *domain.DomainError)); ok {
		return returnFunc(ctx, comment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.BlogComment) *domain.BlogComment); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BlogComment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.BlogComment) *domain.DomainError); ok {
		r1 = returnFunc(ctx, comment)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.DomainError)
		}
	}
	return r0, r1
}

// MockBlogCommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBlogCommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - comment *domain.BlogComment
func (_e *MockBlogCommentRepository_Expecter) Create(ctx interface{}, comment interface{}) *MockBlogCommentRepository_Create_Call {
	return &MockBlogCommentRepository_Create_Call{Call: _e.mock.On("Create", ctx, comment)}
}

func (_c *MockBlogCommentRepository_Create_Call) Run(run func(ctx context.Context, comment *domain.BlogComment)) *MockBlogCommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.BlogComment
		if args[1] != nil {
			arg1 = args[1].(*domain.BlogComment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlogCommentRepository_Create_Call) Return(blogComment *domain.BlogComment, domainError *domain.DomainError) *MockBlogCommentRepository_Create_Call {
	_c.Call.Return(blogComment, domainError)
	return _c
}

func (_c *MockBlogCommentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, comment *domain.BlogComment) (*domain.BlogComment, *domain.DomainError)) *MockBlogCommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBlogCommentRepository
func (_mock *MockBlogCommentRepository) Delete(ctx context.Context, id string) *domain.DomainError {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *domain.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.DomainError); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DomainError)
		}
	}
	return r0
}

// MockBlogCommentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBlogCommentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBlogCommentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockBlogCommentRepository_Delete_Call {
	return &MockBlogCommentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBlogCommentRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockBlogCommentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlogCommentRepository_Delete_Call) Return(domainError *domain.DomainError) *MockBlogCommentRepository_Delete_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockBlogCommentRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) *domain.DomainError) *MockBlogCommentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentByID provides a mock function for the type MockBlogCommentRepository
func (_mock *MockBlogCommentRepository) GetCommentByID(ctx context.Context, id string) (*domain.BlogComment, *domain.DomainError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentByID")
	}

	var r0 *domain.BlogComment
	var r1 *domain.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.BlogComment, *domain.DomainError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.BlogComment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BlogComment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *domain.DomainError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.DomainError)
		}
	}
	return r0, r1
}

// MockBlogCommentRepository_GetCommentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentByID'
type MockBlogCommentRepository_GetCommentByID_Call struct {
	*mock.Call
}

// GetCommentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBlogCommentRepository_Expecter) GetCommentByID(ctx interface{}, id interface{}) *MockBlogCommentRepository_GetCommentByID_Call {
	return &MockBlogCommentRepository_GetCommentByID_Call{Call: _e.mock.On("GetCommentByID", ctx, id)}
}

func (_c *MockBlogCommentRepository_GetCommentByID_Call) Run(run func(ctx context.Context, id string)) *MockBlogCommentRepository_GetCommentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlogCommentRepository_GetCommentByID_Call) Return(blogComment *domain.BlogComment, domainError *domain.DomainError) *MockBlogCommentRepository_GetCommentByID_Call {
	_c.Call.Return(blogComment, domainError)
	return _c
}

func (_c *MockBlogCommentRepository_GetCommentByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.BlogComment, *domain.DomainError)) *MockBlogCommentRepository_GetCommentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentsByBlogID provides a mock function for the type MockBlogCommentRepository
func (_mock *MockBlogCommentRepository) GetCommentsByBlogID(ctx context.Context, blogID string, limit int) ([]domain.BlogComment, *domain.DomainError) {
	ret := _mock.Called(ctx, blogID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentsByBlogID")
	}

	var r0 []domain.BlogComment
	var r1 *domain.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.BlogComment, *domain.DomainError)); ok {
		return returnFunc(ctx, blogID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []domain.BlogComment); ok {
		r0 = returnFunc(ctx, blogID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BlogComment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) *domain.DomainError); ok {
		r1 = returnFunc(ctx, blogID, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.DomainError)
		}
	}
	return r0, r1
}

// MockBlogCommentRepository_GetCommentsByBlogID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentsByBlogID'
type MockBlogCommentRepository_GetCommentsByBlogID_Call struct {
	*mock.Call
}

// GetCommentsByBlogID is a helper method to define mock.On call
//   - ctx context.Context
//   - blogID string
//   - limit int
func (_e *MockBlogCommentRepository_Expecter) GetCommentsByBlogID(ctx interface{}, blogID interface{}, limit interface{}) *MockBlogCommentRepository_GetCommentsByBlogID_Call {
	return &MockBlogCommentRepository_GetCommentsByBlogID_Call{Call: _e.mock.On("GetCommentsByBlogID", ctx, blogID, limit)}
}

func (_c *MockBlogCommentRepository_GetCommentsByBlogID_Call) Run(run func(ctx context.Context, blogID string, limit int)) *MockBlogCommentRepository_GetCommentsByBlogID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlogCommentRepository_GetCommentsByBlogID_Call) Return(blogComments []domain.BlogComment, domainError *domain.DomainError) *MockBlogCommentRepository_GetCommentsByBlogID_Call {
	_c.Call.Return(blogComments, domainError)
	return _c
}

func (_c *MockBlogCommentRepository_GetCommentsByBlogID_Call) RunAndReturn(run func(ctx context.Context, blogID string, limit int) ([]domain.BlogComment, *domain.DomainError)) *MockBlogCommentRepository_GetCommentsByBlogID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBlogCommentRepository
func (_mock *MockBlogCommentRepository) Update(ctx context.Context, id string, comment *domain.BlogComment) (*domain.BlogComment, *domain.DomainError) {
	ret := _mock.Called(ctx, id, comment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.BlogComment
	var r1 *domain.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.BlogComment) (*domain.BlogComment, *domain.DomainError)); ok {
		return returnFunc(ctx, id, comment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.BlogComment) *domain.BlogComment); ok {
		r0 = returnFunc(ctx, id, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BlogComment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *domain.BlogComment) *domain.DomainError); ok {
		r1 = returnFunc(ctx, id, comment)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.DomainError)
		}
	}
	return r0, r1
}

// MockBlogCommentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBlogCommentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - comment *domain.BlogComment
func (_e *MockBlogCommentRepository_Expecter) Update(ctx interface{}, id interface{}, comment interface{}) *MockBlogCommentRepository_Update_Call {
	return &MockBlogCommentRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, comment)}
}

func (_c *MockBlogCommentRepository_Update_Call) Run(run func(ctx context.Context, id string, comment *domain.BlogComment)) *MockBlogCommentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *domain.BlogComment
		if args[2] != nil {
			arg2 = args[2].(*domain.BlogComment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlogCommentRepository_Update_Call) Return(blogComment *domain.BlogComment, domainError *domain.DomainError) *MockBlogCommentRepository_Update_Call {
	_c.Call.Return(blogComment, domainError)
	return _c
}

func (_c *MockBlogCommentRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id string, comment *domain.BlogComment) (*domain.BlogComment, *domain.DomainError)) *MockBlogCommentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
