// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain_mocks

import (
	"context"
	"g6/blog-api/Domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBlogUserReactionRepository creates a new instance of MockBlogUserReactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlogUserReactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlogUserReactionRepository {
	mock := &MockBlogUserReactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlogUserReactionRepository is an autogenerated mock type for the BlogUserReactionRepository type
type MockBlogUserReactionRepository struct {
	mock.Mock
}

type MockBlogUserReactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlogUserReactionRepository) EXPECT() *MockBlogUserReactionRepository_Expecter {
	return &MockBlogUserReactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockBlogUserReactionRepository
func (_mock *MockBlogUserReactionRepository) Create(ctx context.Context, reaction *domain.BlogUserReaction) (*domain.BlogUserReaction, *domain.DomainError) {
	ret := _mock.Called(ctx, reaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.BlogUserReaction
	var r1 *domain.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.BlogUserReaction) (*domain.BlogUserReaction, *domain.DomainError)); ok {
		return returnFunc(ctx, reaction)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.BlogUserReaction) *domain.BlogUserReaction); ok {
		r0 = returnFunc(ctx, reaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BlogUserReaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.BlogUserReaction) *domain.DomainError); ok {
		r1 = returnFunc(ctx, reaction)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.DomainError)
		}
	}
	return r0, r1
}

// MockBlogUserReactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBlogUserReactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - reaction *domain.BlogUserReaction
func (_e *MockBlogUserReactionRepository_Expecter) Create(ctx interface{}, reaction interface{}) *MockBlogUserReactionRepository_Create_Call {
	return &MockBlogUserReactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, reaction)}
}

func (_c *MockBlogUserReactionRepository_Create_Call) Run(run func(ctx context.Context, reaction *domain.BlogUserReaction)) *MockBlogUserReactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.BlogUserReaction
		if args[1] != nil {
			arg1 = args[1].(*domain.BlogUserReaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlogUserReactionRepository_Create_Call) Return(blogUserReaction *domain.BlogUserReaction, domainError *domain.DomainError) *MockBlogUserReactionRepository_Create_Call {
	_c.Call.Return(blogUserReaction, domainError)
	return _c
}

func (_c *MockBlogUserReactionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, reaction *domain.BlogUserReaction) (*domain.BlogUserReaction, *domain.DomainError)) *MockBlogUserReactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBlogUserReactionRepository
func (_mock *MockBlogUserReactionRepository) Delete(ctx context.Context, id string) *domain.DomainError {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *domain.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.DomainError); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DomainError)
		}
	}
	return r0
}

// MockBlogUserReactionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBlogUserReactionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBlogUserReactionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockBlogUserReactionRepository_Delete_Call {
	return &MockBlogUserReactionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBlogUserReactionRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockBlogUserReactionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlogUserReactionRepository_Delete_Call) Return(domainError *domain.DomainError) *MockBlogUserReactionRepository_Delete_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockBlogUserReactionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) *domain.DomainError) *MockBlogUserReactionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserReaction provides a mock function for the type MockBlogUserReactionRepository
func (_mock *MockBlogUserReactionRepository) GetUserReaction(ctx context.Context, blogID string, userID string) (*domain.BlogUserReaction, *domain.DomainError) {
	ret := _mock.Called(ctx, blogID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReaction")
	}

	var r0 *domain.BlogUserReaction
	var r1 *domain.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.BlogUserReaction, *domain.DomainError)); ok {
		return returnFunc(ctx, blogID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.BlogUserReaction); ok {
		r0 = returnFunc(ctx, blogID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BlogUserReaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *domain.DomainError); ok {
		r1 = returnFunc(ctx, blogID, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.DomainError)
		}
	}
	return r0, r1
}

// MockBlogUserReactionRepository_GetUserReaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserReaction'
type MockBlogUserReactionRepository_GetUserReaction_Call struct {
	*mock.Call
}

// GetUserReaction is a helper method to define mock.On call
//   - ctx context.Context
//   - blogID string
//   - userID string
func (_e *MockBlogUserReactionRepository_Expecter) GetUserReaction(ctx interface{}, blogID interface{}, userID interface{}) *MockBlogUserReactionRepository_GetUserReaction_Call {
	return &MockBlogUserReactionRepository_GetUserReaction_Call{Call: _e.mock.On("GetUserReaction", ctx, blogID, userID)}
}

func (_c *MockBlogUserReactionRepository_GetUserReaction_Call) Run(run func(ctx context.Context, blogID string, userID string)) *MockBlogUserReactionRepository_GetUserReaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlogUserReactionRepository_GetUserReaction_Call) Return(blogUserReaction *domain.BlogUserReaction, domainError *domain.DomainError) *MockBlogUserReactionRepository_GetUserReaction_Call {
	_c.Call.Return(blogUserReaction, domainError)
	return _c
}

func (_c *MockBlogUserReactionRepository_GetUserReaction_Call) RunAndReturn(run func(ctx context.Context, blogID string, userID string) (*domain.BlogUserReaction, *domain.DomainError)) *MockBlogUserReactionRepository_GetUserReaction_Call {
	_c.Call.Return(run)
	return _c
}
